title: James Mulvihill
logo: PXL_20241222_183609332.jpg
description: Hi, I'm James. This is my data science portfolio. I come from a software developement background, most recently focusing on police software.
#show_downloads: true
theme: jekyll-theme-minimal
